Revert "updates at dfinstall"
This reverts commit c7b7505aec1608ddaf03909c6d09622ba74294a0.

diff --git a/customscripts/dfinstall b/customscripts/dfinstall
--- a/customscripts/dfinstall
+++ b/customscripts/dfinstall
@@ -1,6 +1,6 @@
 #!/bin/bash
 function usage {
-       echo "Usage: dfinstall -s dotfiles_path [-c config_file] [-f]
+       echo "Usage: dfinstall -s dotfiles_path [-c config_file]
          -s                          path of the dotfiles DIRECTORY.
          -c                          config file (mapping) 
                                      format:
@@ -9,7 +9,6 @@ function usage {
                                           src:destination
                                           EOF
                                    [default: dotfiles_path/.linkmap]
-         -f                          Force creation if file doesn't exists     
          -h                          Display this help message.
 
 dfinstall installs all the dotfiles mapped at .linkmap in the source folder"
@@ -19,12 +18,10 @@ dfinstall installs all the dotfiles mapped at .linkmap in the source folder"
 #Getting params
 dotfiles_path='';
 config_file='';
-force=false;
-while getopts :s:c:fh opt; do
+while getopts :s:c:h opt; do
     case ${opt} in
       s) dotfiles_path=${OPTARG};;
       c) config_file=${OPTARG};;
-      f) force=true;;
       h) usage ;;
       *) echo "Invalid Option";usage;;
      esac
@@ -44,19 +41,11 @@ fi
 
 #link subfile function
 function linkfile(){
-       if [[ $# -gt 2 ]]; then 
-              sourcefile=${1/$3/$2};targetfile=$1
-       else
-              sourcefile=$1;targetfile=$2
-       fi
-       
-       if [[ -f $sourcefile ]] || ! [[ -f $sourcefile ]] && $force; then
+       [[ $# -gt 2 ]] && sourcefile=${1/$3/$2};targetfile=$1 || sourcefile=$1;targetfile=$2
+       [[ -f $sourcefile ]] && 
               echo "[+] Linking File: $sourcefile -> $targetfile";
-              rm "$sourcefile";
-              ln -sf $(realpath $targetfile) "$sourcefile";
-       else
-              echo "[!] File not found (Use -f to force creation of file): $sourcefile";
-       fi
+              ln -sf "$target" "$sourcefile"
+       || echo "[!] File not found: $sourcefile";
 }
 export -f linkfile;
 
