Added light-changer script, Improved kipin script, Added .desktop files to linkmap, deleted a lot of unused scripts, slightly refactored (work in progress) the eww.yuck file, Added new icon

diff --git a/customscripts/kipin/kipin-front b/customscripts/kipin/kipin-front
--- a/customscripts/kipin/kipin-front
+++ b/customscripts/kipin/kipin-front
@@ -1,4 +1,16 @@
 #!/bin/bash
-cd ~/proyectos/kipin/webapp || exit; 
+
+#Checking that first parameter is a valid path
+if [ ! -d "$1" ]; then
+    echo "Error: $1 is not a valid path"
+    exit 1
+fi
+
+root_dir="$1";
+
+# Change directory to root_dir
+cd "$root_dir" || exit; 
+
+# Start front end
 export NODE_OPTIONS=--openssl-legacy-provider;
 npx ng s;
diff --git a/customscripts/kipin/kipin-socket b/customscripts/kipin/kipin-socket
--- a/customscripts/kipin/kipin-socket
+++ b/customscripts/kipin/kipin-socket
@@ -1,2 +1,14 @@
 #!/bin/bash
-cd ~/proyectos/kipin/socketserver_ts; npm start; sleep 10
+
+#Checking that first parameter is a valid path
+if [ ! -d "$1" ]; then
+    echo "Error: $1 is not a valid path"
+    exit 1
+fi
+root_dir="$1";
+
+# Change directory to root_dir
+cd "$root_dir" || exit; 
+
+# Start socketserver
+npm start; 
